# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-14 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='user',
        ),
        migrations.AddField(
            model_name='score',
            name='name',
            field=models.CharField(default='Satan', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
